/** Random values can be generated by Math.random().
 *
 *  Math.random() returns a double value with positive sign, greater
 *  than or equal to 0.0 and less than 1.0. Unlike other methods in
 *  the Math class, it does not return always the same value, but
 *  typically each time a different value so that the returned values
 *  are approximately uniformly distributed. It makes use of a "pseudo
 *  random-number generator".
 *
 *  @author  Manfred Kerber
 *  @version 2018-08-20
 *
 */

public class Computation5 { 

    public static void main(String[] args) {
       System.out.print("System.out.println(Math.random());  ==> "); System.out.println(Math.random());
       System.out.print("System.out.println(Math.random());  ==> "); System.out.println(Math.random());
       System.out.print("System.out.println(Math.random());  ==> "); System.out.println(Math.random());

   }
}
